package com.farmacia.cristoredentor.Enum;

public enum CategoriaProducto {
    ANTIBIOTICOS,
    ANTIHIPERTENSIVOS,
    ANTIDIABETICOS,
    ANALGESICOS,
    ANTIINFLAMATORIOS,
    ANTIHISTAMINICOS,
    ANTIGRIPALES,
    PROTECTORES_GASTRICOS,
    CARDIOLOGICOS,
    RESPIRATORIOS,
    DERMATOLOGICOS,
    VITAMINAS_SUPLEMENTOS,
    INSUMOS_MEDICOS,
    CUIDADO_PERSONAL,
    PEDIATRICO,
    ORTOPEDIA,
    OTROS
}
